apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: deploy-onion
  namespace: flux-system
spec:
#  dependsOn:
#    - name: tor-controller-crds
#      namespace: flux-system
  interval: 5m
  path: ./base/nginx/onionservice.yaml
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
