apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tor-controller
  namespace: flux-system
spec:
  interval: 10m
  chart:
    spec:
      chart: tor-controller
      version: '*'
      sourceRef:
        kind: HelmRepository
        name: tor-controller
      interval: 5m
#      values:
#        installCRDs: false
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
