apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: trinami.zip.source
  namespace: cert-manager
spec:
  secretName: trinami.zip.source
  privateKey:
    algorithm: RSA
    size: 4096
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
    group: cert-manager.io
  commonName: "*.trinami.zip"
  dnsNames:
    - "trinami.zip"
    - "*.trinami.zip"
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "api,cryptpad,gitea,jitsi,matrix,prometheus,vaultwarden,calendar,webtop,www,nexus,jenkins,minecraft,trivy,mail,proxy,cloud,keycloak"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "api,cryptpad,gitea,jitsi,matrix,prometheus,vaultwarden,calendar,webtop,www,nexus,jenkins,minecraft,trivy,mail,proxy,cloud,keycloak"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: trinami.org.source
  namespace: cert-manager
spec:
  secretName: trinami.org.source
  privateKey:
    algorithm: RSA
    size: 4096
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
    group: cert-manager.io
  commonName: "*.trinami.org"
  dnsNames:
    - "trinami.org"
    - "*.trinami.org"
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "api,cryptpad,gitea,jitsi,matrix,prometheus,vaultwarden,calendar,webtop,www,nexus,jenkins,minecraft,trivy,mail,proxy,cloud,keycloak"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "api,cryptpad,gitea,jitsi,matrix,prometheus,vaultwarden,calendar,webtop,www,nexus,jenkins,minecraft,trivy,mail,proxy,cloud,keycloak"
