apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: eric@gmx.net
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - dns01:
        cloudflare:
          email: ericmc@outlook.de
          apiTokenSecretRef:
            name: cloudflare-dns
            key: cloudflare-apikey
      selector:
        dnsNames:
        - 'trinami.zip'
        - '*.trinami.zip'
        - 'trinami.org'
        - '*.trinami.org'
